# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MName', models.CharField(help_text='Enter Mall Name', max_length=255)),
                ('MAddress', models.CharField(help_text='Enter Address of the Mall', max_length=255)),
                ('M_image', models.ImageField(upload_to='media/document/%Y/%m/%d/')),
                ('M_Status', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('MCategory', models.ManyToManyField(blank=True, to='api.Category', verbose_name='Product categories')),
            ],
        ),
    ]
