# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_shop_shop_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_name', models.CharField(help_text='Enter Employee Name', max_length=255)),
                ('Emp_email', models.CharField(help_text='Enter Email', max_length=255)),
                ('Emp_age', models.CharField(help_text='Enter age', max_length=255)),
                ('Emp_salary', models.CharField(help_text='Enter Salary', max_length=255)),
                ('Emp_image', models.ImageField(upload_to='media/document/%y/%m/%d/')),
                ('Emp_role', models.CharField(choices=[('c1', 'choice1'), ('c2', 'choice2'), ('c3', 'choice3'), ('o', 'other')], max_length=1)),
                ('Emp_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Emp_status', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('W_mall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Mall')),
                ('W_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Shop')),
            ],
        ),
    ]
