# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='Product_type',
            field=models.ManyToManyField(blank=True, to='api.Product', verbose_name='Shop type'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='S_status',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'close'), ('S', 'shifted'), ('o', 'other')], max_length=1),
        ),
    ]
