# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20171208_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='PT_status',
        ),
        migrations.AlterField(
            model_name='mall',
            name='MCategory',
            field=models.ManyToManyField(blank=True, to='api.Category', verbose_name='Mall Categories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PT_status',
            field=models.CharField(choices=[('A', 'Avilable'), ('NA', 'Not Avilable'), ('N', 'New stoke'), ('Ol', 'Old stoke'), ('O', 'Others')], max_length=1),
        ),
        migrations.AlterField(
            model_name='shop',
            name='S_status',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Close'), ('S', 'Shifted'), ('o', 'Other')], max_length=1),
        ),
    ]
