# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20171208_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='PT_status',
            new_name='P_status',
        ),
    ]
