# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20171208_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Emp_email',
            field=models.EmailField(blank=True, help_text='Enter Email', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Emp_status',
            field=models.CharField(choices=[('D', 'on-duty'), ('L', 'leave'), ('W', 'Weekly off'), ('O', 'Other')], max_length=1),
        ),
    ]
