# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_user1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User1',
        ),
    ]
