# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20171231_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product')),
            ],
        ),
        migrations.AddField(
            model_name='mall',
            name='thumb_pic',
            field=models.ImageField(blank=True, null=True, upload_to='mall/thumb/'),
        ),
        migrations.AlterField(
            model_name='mall',
            name='M_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/document/product/%Y/%m/%d/'),
        ),
    ]
